apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gke-node-optimizer:gke-node-optimizer:cluster-admin
subjects:
  - kind: ServiceAccount
    name: gke-node-optimizer
    namespace: gke-node-optimizer
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
