apiVersion: v1
kind: ServiceAccount
metadata:
  name: gke-node-optimizer
  namespace: gke-node-optimizer
  annotations:
    # FIXME: Specify the your gcp project
    # - add roles: roles/container.clusterViewer, roles/compute.instanceAdmin.v1
    iam.gke.io/gcp-service-account: "gke-node-optimizer@<YOUR_GCP_PROJECT>.iam.gserviceaccount.com"